name			= "Knights of Ryxis";					// Name of your mod
author			= "Gigasus / Stone";				// Affects Arma 3 Launcher, when the mod are loaded as local
logo			= "logo.paa";			// Logo displayed in the main menu
logoOver		= "logoOver.paa";	// When the mouse is over, in the main menu
tooltip			= "Knights of Ryxis";
tooltipOwned	= "Retexture for the Knights of Ryxis";				// Tool tip displayed when the mouse is left over, in the main menu
picture			= "picture.paa";		// Picture displayed from the expansions menu. Optimal size is 2048x1024
actionName		= "GitHub";
action			= "https://github.com/my-mod-page";			// Website URL, that can be accessed from the expansions menu
overview		= "Retexture of Knights of Ryxis from mods such as There is only War, Crossing the Rubicon and Project Primaris.";	// Supports structured text
hideName		= 0;						// Hide the extension name
hidePicture		= 0;						// Hide the extension menu
dlcColor[]		= { 0.23, 0.39, 0.30, 1 };	// Color used for DLC stripes and backgrounds (RGBA)
logoSmall		= "logo_small.paa";		// Display in creative lists, next to the entities added by the mod